# Generated by Django 5.2.7 on 2025-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobmodel',
            name='applied_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
