# Generated by Django 5.2.7 on 2025-10-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_applyjobmodel_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
